Repository Brains-Beyond-Expectations/bbe-quest, pull requests merged in 2025-03, with the labels that each got.

#23 test(config service): increase coverage
  cli/mocks/os_mock.go
  cli/services/config_service/config_service.go
  cli/services/config_service/config_service_test.go
Labels: chore, patch

#13 feat(nginx): Add ingress nginx #12
  .gitignore
  cli/services/package_service/package_service.go
  cli/services/package_service/package_service_test.go
  codecov.yaml
Labels: enhancement, minor

#24 test: removed all coverage comments from previous tool, ignored a couple files that we are unliky to test
  cli/cmd/cmd.go
  cli/cmd/config.go
  cli/cmd/install.go
  cli/cmd/setup.go
  cli/cmd/upgrade.go
  cli/main.go
  cli/misc/logger/logger.go
  cli/services/s3_service/s3_service.go
  cli/services/ui_service/ui_service.go
  codecov.yaml
Labels: chore, patch

#29 fix: package installation
  cli/services/package_service/package_service.go
  cli/services/package_service/package_service_test.go
Labels: bug, patch
