Repository Brains-Beyond-Expectations/bbe-quest, pull requests merged in 2025-02, with the labels that each got.

#11 fix(packages): Typo on helm install
  .vscode/launch.json
  cli/services/package_service/package_service.go
Labels: bug, patch

#14 chore: improve ping test
  cli/services/talos_service/talos_service_test.go
Labels: chore, patch

#10 fix(initialization): Fix when no node is present during initialization
  .pre-commit-config.yaml
  README.md
  cli/cmd/setup.go
  cli/cmd/setup_test.go
Labels: bug, patch

#15 fix: make sure to always use bbe cluster context
  cli/cmd/install.go
  cli/interfaces/packages_service.go
  cli/mocks/package_service_mock.go
  cli/models/bbe_config.go
  cli/models/package.go
  cli/services/config_service/config_service.go
  cli/services/package_service/package_service.go
  cli/services/package_service/package_service_test.go
Labels: bug, patch

#20 feat: compile releases for darwin + minor refactoring
  .github/workflows/main.yaml
  cli/cmd/setup.go
  cli/cmd/setup_test.go
Labels: enhancement, minor

#17 feat: upgrade packages
  cli/cmd/upgrade.go
  cli/cmd/upgrade_test.go
  cli/interfaces/packages_service.go
  cli/mocks/package_service_mock.go
  cli/services/package_service/package_service.go
  cli/services/package_service/package_service_test.go
Labels: enhancement, minor

#22 chore: run tests on main workflow
  .github/workflows/main.yaml
Labels: chore, patch
